name: Parallel Testing
on: 
    workflow_dispatch:
    pull_request:
        branches:
            - main
jobs:
    parallel-tests:
        name: Parallel Testing Demo
        runs-on: ubuntu-latest
        strategy:
            matrix:
                machines: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run the tests
              uses: cypress-io/github-action@v2
              with:
                browser: chrome
                record: true
                parallel: true
                group: 'ATD_DEMO'
                tag: "Parallel"
              env: 
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}      
