name: Sequential Testing
on: 
    workflow_dispatch:
jobs:
    parallel-tests:
        name: Sequential Testing Demo
        runs-on: ubuntu-latest
        strategy:
            matrix:
                machines: [1, 2, 3]
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Run the tests
              uses: cypress-io/github-action@v2
              with:
                browser: firefox
                record: true
                group: 'ATD_DEMO'
                tag: "Sequential"
              env: 
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}      
